[F01][ZS03] Create API function for getting data
Nicomagg/academy-react-native-2021 pull request #13
Opened 2021-07-15 18:55 UTC by zoesobol

2021-07-15 19:38 UTC, Nicomagg requested changes
@zoesobol creaste el PR a main y no a develop. Fijate si se puede camibar en este PR mismo o declinalo y create otro 👍

2021-07-15 19:55 UTC, zoesobol commented
ahí cambié @Nicomagg !

2021-07-15 20:11 UTC, facuhacosta approved these changes

2021-07-15 20:40 UTC, Nicomagg requested changes
El **Request changes** es solo por el `try/catch` faltante. El resto son recomendaciones.

2021-07-15 20:40 UTC, Nicomagg commented on ZoeSobol/App.js
> +      const res = await fetch(url);
Falta un `try{...}catch(){...}` por si hay errores en el `fetch` o en el `.json()` como para mostrarle un mensaje de error elegante al usuario y que no se cierre la app directamente.

2021-07-15 20:40 UTC, Nicomagg commented on ZoeSobol/App.js
> +    setCurrentPageUrl(nextPageUrl);
Mucho cuidado con el manejo de url de este tipo porque podes caer en un error según el comportamiento del usuario. Lo mejor es tener un Cliente genérico encargado de hacer las llamadas y según la acción pasarle una url donde hacer la llamada.

2021-07-15 20:40 UTC, Nicomagg commented on ZoeSobol/components/Pagination.js
> +      <Button key={i} onPress={() => goToPage(i)} title={i + ""} />
Cuidado que la `key` es muy genérica y te puede traer problemas de performance según si un componente tiene lo mismo. En estos casos podes hacer algo como `key={`Button-Pagination-${i}`}`

2021-07-15 20:40 UTC, Nicomagg commented on ZoeSobol/App.js
> +        <ScrollView
Veo que `Home` tiene un map de componentes. Acordate que para lista de componentes iguales, lo mejor es un `FlatList`. En las props podes pasarle un componente `Header` o `Footer` por si necesitas mostrar algo arriba o abajo de la lista (aclaro por si usaste un `ScrollView` por ese motivo)

2021-07-16 12:25 UTC, facuhacosta approved these changes

2021-07-19 12:10 UTC, mauroluis approved these changes

2021-07-20 12:38 UTC, Nicomagg approved these changes

2021-07-20 12:42 UTC, merged