Feature/f01 fa02
Nicomagg/academy-react-native-2021 pull request #6
Opened 2021-07-14 16:26 UTC by facuhacosta

Adding feth to API first page and basic preview

2021-07-14 17:42 UTC, lucasmmaidana approved these changes

2021-07-14 20:25 UTC, Nicomagg requested changes
El **Request changes** es por el catch faltante en el fetch. Si lo tenes en otra tarea agregar eso, avisame y lo cambiamos a **Approve**.

2021-07-14 20:25 UTC, Nicomagg commented on FacundoAcosta/App.js
> +      <View>
No estoy seguro si es necesario este `View` ya que el `Home` también lo envuelve un `View`. No se si me explico?  No es malo tampoco, solo lo comento para que sea consciente agregar esos contenedores y no agregar a lo loco nomas 😄

2021-07-14 20:25 UTC, Nicomagg commented on FacundoAcosta/Components/home.js
> +        fetch('https://rickandmortyapi.com/api/character')
Le falta un `catch` en tu fetch por si hay un error. No se si viene en una próxima user esto pero trata de agregarlo por si llega a fallar algo no se rompa toda la app y mostremos algún mensaje bonito 👍

2021-07-15 00:16 UTC, facuhacosta commented on FacundoAcosta/Components/home.js
> +import React, { useContext, useEffect, useState } from 'react';
en el proximo ya remuevo estos que estan de más

2021-07-15 13:31 UTC, Nicomagg approved these changes

2021-07-15 13:33 UTC, merged